"""VF3 pinned to the recorded on-air captures, stage by stage.

`tests/test_vf3_kernels.py` holds the two vectorized kernels to their scalar
originals.  This file holds the *whole 12 kHz receive decode* -- acquisition, the timing
regression, the header channel fit, the soft-bit mapper, the Viterbi input
and the CRC -- to what it produced on real HF audio, so that lifting those
stages into `whale/dsp/` can be shown to change nothing.

The goldens are regenerated by `scripts/make_vf3_golden.py`, which is also
where the choice of captures and pinned keys is explained.  A digest that
moves is not automatically a bug, but it is never an incidental diff: it
means a frame that used to decode one way now decodes another, and that has
to be justified before the baseline is moved.

Software only -- no radios, no sound cards.
"""

import json
import pathlib

import numpy as np
import pytest

from whale import rx_audio
from whale.modes import vf3
from scripts.make_vf3_golden import (CAPTURES, EXACT_ARRAY_KEYS, SCALAR_KEYS,
                                     TOLERANCE_ARRAY_KEYS, deserialize, digest)

GOLDEN_PATH = pathlib.Path(__file__).parent / "data" / "vf3_capture_golden.json"
GOLDEN = json.loads(GOLDEN_PATH.read_text())

# Scalars, and most of the pinned arrays, are compared to a tight relative
# tolerance rather than bit-exact -- numpy's reductions are not required to
# be bit-identical across BLAS builds (e.g. Apple's Accelerate vs. OpenBLAS),
# and holding them to that would make the suite fail on a different machine
# rather than on a real regression.  Only EXACT_ARRAY_KEYS (the
# hard-decision Viterbi input) is pinned bit-exact, since thresholding makes
# it stable across backends.
FLOAT_TOLERANCE = 1e-9


def capture_ids():
    return sorted(GOLDEN)


@pytest.fixture(scope="module")
def decoded():
    """Every pinned capture decoded once; the frames are 5.2 s each."""
    results = {}
    for name in capture_ids():
        audio = np.load(CAPTURES / name)
        results[name] = vf3.demodulate(rx_audio.downsample(audio))
    return results


@pytest.mark.parametrize("name", capture_ids())
def test_capture_still_decodes_to_its_transmitted_payload(name, decoded):
    expected = (CAPTURES / name).with_suffix(".bin").read_bytes()
    result = decoded[name]
    assert result["synced"] is True
    assert result["crc_ok"] is True
    assert result["payload"] == expected


@pytest.mark.parametrize("name", capture_ids())
def test_capture_decode_stages_are_bit_for_bit_unchanged(name, decoded):
    result = decoded[name]
    expected = GOLDEN[name]["arrays"]
    actual = {key: digest(np.asarray(result[key])) for key in EXACT_ARRAY_KEYS}
    assert actual == {key: expected[key] for key in EXACT_ARRAY_KEYS}


@pytest.mark.parametrize("name", capture_ids())
def test_capture_decode_stages_are_unchanged_within_tolerance(name, decoded):
    result = decoded[name]
    expected = GOLDEN[name]["arrays"]
    for key in TOLERANCE_ARRAY_KEYS:
        actual = np.asarray(result[key])
        golden = deserialize(expected[key])
        assert np.allclose(actual, golden, rtol=FLOAT_TOLERANCE,
                           atol=FLOAT_TOLERANCE), key


@pytest.mark.parametrize("name", capture_ids())
def test_capture_decode_scalars_are_unchanged(name, decoded):
    result = decoded[name]
    golden = GOLDEN[name]
    for key in SCALAR_KEYS:
        value = result[key]
        if isinstance(golden[key], bool):
            assert bool(value) is golden[key], key
        elif isinstance(golden[key], int):
            assert int(value) == golden[key], key
        else:
            assert value == pytest.approx(
                golden[key], rel=FLOAT_TOLERANCE), key


def test_the_golden_file_covers_the_dqpsk_captures_actually_present():
    """Guards against the goldens silently going empty or stale.

    A capture set that is added, renamed or deleted should force a
    deliberate re-baseline rather than quietly shrinking what is pinned.
    """
    from scripts.make_vf3_golden import capture_paths

    on_disk = {str(path.relative_to(CAPTURES)).replace("\\", "/")
               for path in capture_paths()}
    assert on_disk == set(GOLDEN)
    assert len(on_disk) == 8
